Add lso ipv4 primary vlan test

diff --git a/illumos/net-tests/lso-tests b/illumos/net-tests/lso-tests
--- a/illumos/net-tests/lso-tests
+++ b/illumos/net-tests/lso-tests
@@ -50,6 +50,61 @@ function test_lso_ip4_primary
 	pass
 }
 
+function test_lso_ip4_primary_vlan
+{
+	typeset send=$1
+	typeset recv=$2
+	typeset send_ip1=${IP4[0]}
+	typeset recv_ip1=${IP4[1]}
+	typeset vid=9
+
+	TNAME="$0<$send>"
+	typeset pcap=/tmp/$TNAME.pcap
+
+	verify_nic $send
+	verify_nic $recv
+
+	#
+	# The ipv4 hostmodel must be set to src-priority so that two
+	# interfaces on the same subnet will NOT go over the local
+	# route but instead be sent across the physical interfaces.
+	#
+	verify_ip4_hostmodel
+
+	typeset send_vlan=$(create_vlan $send $vid)
+	typeset recv_vlan=$(create_vlan $recv $vid)
+
+	create_addr $send_vlan $send_ip1
+	create_addr $recv_vlan $recv_ip1
+
+	# Assumes untagged for now.
+	typeset mtu=$(get_mtu $send)
+	typeset maxpkt=$((mtu + 14))
+
+	#
+	# Capture only packets larger than MTU, if pcap is empty we
+	# know we failed.
+	#
+	typeset filt="(src $send_ip1) and (dst $recv_ip1) and (greater $maxpkt)"
+	$SNOOP -q -d $send_vlan -o $pcap "$filt" > /dev/null 2>&1 &
+	typeset snoop_pid=$!
+
+	send_traffic $send_ip1 $recv_ip1 $recv_vlan
+
+	kill -s TERM $snoop_pid
+	if ! $SNOOP -p 1 -i $pcap | grep "Len=" > /dev/null
+	then
+		fail "$send sent no packets greater than MTU"
+	fi
+
+	# TODO: modify to take multiple args to delete at once.
+	delete_interface $send_vlan
+	delete_interface $recv_vlan
+	delete_vlan $send_vlan
+	delete_vlan $recv_vlan
+	pass
+}
+
 #
 # Verify IPv6 LSO on primary interface of $send.
 #
@@ -494,6 +549,7 @@ send_nic=$1
 recv_nic=$2
 
 test_lso_ip4_primary $send_nic $recv_nic
+test_lso_ip4_primary_vlan $send_nic $recv_nic
 test_lso_ip4_vnic $send_nic $recv_nic
 test_lso_ip4_mac_loopback $send_nic $recv_nic
 
@@ -510,6 +566,5 @@ test_lso_ip6_mac_loopback $send_nic
 
 echo
 echo "TODO"
-echo "\to VLAN ip4/ip6 primary test"
-echo "\to VLAN ip4/ip6 VNIC tests"
+echo "\to VLAN VNIC ip4/ip6 tests"
 echo "\to VLAN VNIC ip4/ip6 mac-loopback tests"
